/*Create database*/
create database ab78727_exam


/* create table of language*/
create table Language
(
Lang_ID int primary key identity(1,1),
Lang_Name nvarchar(max) not null
)

/*Create table of country*/
create table Country
(
C_ID int identity primary key,
CountryName nvarchar(max) not null,
CountryCode nvarchar(max) not null
)


insert into Country ( CountryName,CountryCode) values
('AFGHANISTAN','+93'),
('ALBANIA','+355'),
('ALGERIA','+213'),
('AMERICAN SAMOA','+1684'),
('ANDORRA','+376'),
('ANGUILLA','+1264'),
('ANTARCTICA','+0'),
('ANTIGUA AND BARBUDA','+1268'),
('ALGERIA','+213'),
('ARGENTINA','+54'),
('ARMENIA','+374'),
('ARUBA','+297'),
('AUSTRALIA','+61'),
('AUSTRIA','+43'),
('AZERBAIJAN','+994'),
('BAHAMAS','+1242'),
('BAHRAIN','+1242'),
('BANGLADESH','+880'),
('BARBADOS','+1246'),
('BELARUS','+375'),
('BELGIUM','+32'),
('BELIZE','+501'),
('BENIN','+229'),
('BERMUDA','+1441'),
('BHUTAN','+975'),
('BOLIVIA','+591'),
('BOSNIA AND HERZEGOVINA','+387'),
('BOTSWANA','+267'),
('BRAZIL', '+55'),

('BRUNEI DARUSSALAM','+ 673'),
('BULGARIA', '+359'),
('BURKINA FASO', '+226'),
('BURUNDI', '+257'),
('CAMBODIA','+855'),
('CAMEROON',  '+237'),
('CANADA', '+1'),
('CAPE VERDE', '+238'),
('CAYMAN ISLANDS', '+1345'),

('CHAD',   '+235'),
('CHILE',  '+56'),
('CHINA',  '+86'),
('CHRISTMAS ISLAND',  '+61'),

('COLOMBIA',  '+57'),
('COMOROS',  '+269'),
('CONGO',  '+242'),
('COOK ISLANDS',  '+682'),
('COSTA RICA', '+506'),
('COTE D IVOIRE', '+225'),
('CROATIA',  '+385'),
('CUBA',  '+53'),
('CYPRUS','+357'),
('CZECH REPUBLIC', '+420'),
('DENMARK', '+45'),
('DJIBOUTI', '+253'),
('DOMINICA',  '+1767'),
('DOMINICAN REPUBLIC',  '+1809'),
('ECUADOR', '+593'),
('EGYPT', '+20'),
( 'EL SALVADOR', '+503'),
('EQUATORIAL GUINEA', '+240'),
( 'ERITREA', '+291'),
( 'ESTONIA', '+372'),
('ETHIOPIA', '+251'),

('FAROE ISLANDS', '+298'),
('FIJI','+679'),
('FINLAND', '+358'),
('FRANCE', '+33'),
( 'FRENCH GUIANA','+594'),
('FRENCH POLYNESIA', '+689'),

( 'GABON', '+241'),
('GAMBIA', '+220'),
( 'GEORGIA', '+995'),
( 'GERMANY', '+49'),
( 'GHANA', '+233'),
( 'GIBRALTAR',  '+350'),
( 'GREECE', '+30'),
( 'GREENLAND',  '+299'),
( 'GRENADA',  '+1473'),
( 'GUADELOUPE',  '+590'),
( 'GUAM','+1671'),
('GUATEMALA',  '+502'),
('GUINEA',  '+224'),
('GUINEA-BISSAU', '+245'),
('GUYANA', '+6592'),
('HAITI', '+509'),

('HONDURAS',  '+504'),
('HONG KONG',  '+852'),
( 'HUNGARY', '+36'),
('ICELAND', '+354'),
('INDIA',  '+91'),
('INDONESIA', '+62'),
('IRAN', '+98'),
('IRAQ', '+964'),
('IRELAND', '+353'),
('ISRAEL',  '+972'),
('ITALY',  '+39'),
('JAMAICA',  '+1876'),
('JAPAN', '+81'),
('JORDAN',  '+962'),
('KAZAKHSTAN',  '+7'),
('KENYA', '+254'),
('KIRIBATI',  '+686'),
('KOREA', '+850'),
('KOREA','+82'),
( 'KUWAIT',  '+965'),
('KYRGYZSTAN',  '+996'),
('LATVIA',  '+371'),
('LEBANON', '+961'),
('LESOTHO','+266'),
('LIBERIA',  '+231'), 
('LIBYAN ARAB JAMAHIRIYA',  '+218'),
('LIECHTENSTEIN',  '+423'),
('LITHUANIA', '+370'),
('LUXEMBOURG', '+352'),
('MACAO',  '+853'),
('MACEDONIA', '+389'),
('MADAGASCAR', '+261'),
('MALAWI', '+265'),
( 'MALAYSIA',  '+60'),
('MALDIVES','+960'),
( 'MALI',  '+223'),
('MALTA', '+356'),
('MARSHALL ISLANDS', '+692'),
('MARTINIQUE', '+596'),
( 'MAURITANIA',  '+222'),
( 'MAURITIUS',  '+230'),
('MAYOTTE',  '+269'),
('MEXICO', '+52'),

( 'MOLDOVA', '+373'),
('MONACO',  '+377'),
( 'MONGOLIA',  '+976'),
( 'MONTSERRAT', '+1664'),
( 'MOROCCO', '+212'),
( 'MOZAMBIQUE', '+258'),
( 'MYANMAR', '+95'),
( 'NAMIBIA',  '+264'),
( 'NAURU', '+674'),
( 'NEPAL', '+977'),
('NETHERLANDS', '+31'),
('NETHERLANDS ANTILLES',  '+599'),
('NEW CALEDONIA',  '+687'),
( 'NEW ZEALAND',  '+64'),
( 'NICARAGUA', '+505'),
('NIGER',  '+227'),
( 'NIGERIA', '+234'),
( 'NIUE', '+683'),
( 'NORFOLK ISLAND',  '+672'),

( 'NORWAY', '+47'),
( 'OMAN', '+968'),
( 'PAKISTAN', '+92'),
( 'PALAU',  '+680'),
('PANAMA', '+507'),
( 'PAPUA NEW GUINEA', '+675'),
('PARAGUAY',  '+595'),
( 'PERU',  '+51'),
( 'PHILIPPINES',  '+63'),
( 'POLAND',  '+48'),
( 'PORTUGAL', '+351'),
( 'PUERTO RICO', '+1787'),
('QATAR', '+974'),
( 'REUNION', '+262'),
( 'ROMANIA',  '+40'),
( 'RUSSIAN FEDERATION',  '+70'),
( 'RWANDA',  '+250'),
( 'SAINT HELENA', '+290'),
( 'SAINT KITTS AND NEVIS', '+1869'),
( 'SAINT LUCIA', '+1758'),
( 'SAINT PIERRE AND MIQUELON','+508'),
( 'SAMOA',  '+684'),
( 'SAN MARINO',  '+378'),
( 'SAO TOME AND PRINCIPE', '+239'),
( 'SAUDI ARABIA', '+966'),
( 'SENEGAL', '+221'),
( 'SERBIA AND MONTENEGRO',  '+381'),
('SEYCHELLES','+248'),
( 'SIERRA LEONE', '+232'),
( 'SINGAPORE',  '+65'),
( 'SLOVAKIA', '+421'),
('SLOVENIA', '+386'),
 ('SOLOMON ISLANDS',  '+677'),
( 'SOMALIA',  '+252'),
( 'SOUTH AFRICA',  '+27'),
( 'SPAIN',  '+34'),
('SRI LANKA',  '+94'),
( 'SUDAN' , '+249'),
( 'SURINAME', '+597'),

('SWAZILAND', '+268'),
( 'SWEDEN',  '+46'),
( 'SWITZERLAND',  '+41'),
( 'SYRIAN ARAB REPUBLIC', '+963'),
('TAIWAN','+886'),
('TAJIKISTAN',  '+992'),
( 'TANZANIA ','+255'),
( 'THAILAND',  '+66'),
('TIMOR-LESTE', '+670'),
( 'TOGO',  '+228'),
( 'TOKELAU',  '+690'),
( 'TONGA',  '+676'),
( 'TUNISIA',  '+216'),
( 'TURKEY', '+90'),
( 'TURKMENISTAN', '+7370'),
('TUVALU', '+688'),
( 'UGANDA',  '+256'),
( 'UKRAINE',  '+380'),
( 'UNITED ARAB EMIRATES',  '+971'),
( 'UNITED KINGDOM', '+44'),
( 'UNITED STATES', '+1'),
( 'URUGUAY', '+598'),
( 'UZBEKISTAN',  '+998'),
('VANUATU',  '+678'),
( 'VENEZUELA', '+58'),
( 'VIET NAM',  '+84'),
('VIRGIN ISLANDS', '+1284'),
('WALLIS AND FUTUNA', '+681'),
( 'WESTERN SAHARA','+212'),
( 'YEMEN',  '+967'),
( 'ZAMBIA',  '+260'),
( 'ZIMBABWE',  '+263')



/*Create table of Hobby*/
create table Hobby
(
Hobby_ID int identity(1,1) primary key,
Hobby_Name nvarchar(max)
)


/*Create table of profession*/
create table Profession
(
Prof_ID int identity(1,1) primary key,
Prof_Name nvarchar(max) not null,
Prof_Country nvarchar(max) not null
)

insert into profession (Prof_Name,Prof_Country)
values
('Aeronautical Society of India','INDIA'),
('Association of Scientists, Developers and Faculties','INDIA'),
('Computer Society of India','INDIA'),
('Engineering Council of India
','INDIA'),
('Engineering Staff College of India
','INDIA'),
('Federation of Indian Photography
','INDIA'),
('Indian Concrete Institute
','INDIA'),
('Indian History Congress
','INDIA'),
('Indian Institute of Architects
','INDIA'),
('Indian Institute of Banking and Finance
','INDIA'),
('Indian Institute of Chemical Engineers
','INDIA'),
('Indian Institute of Metals
','INDIA'),
('Indian Institution of Industrial Engineering
','INDIA'),
('Institute of Actuaries of India
','INDIA'),
('Institute of Company Secretaries of India
','INDIA'),
('Institute of Cost Accountants of India
','INDIA'),
('Institution of Electronics and Telecommunication Engineers
','INDIA'),
('Institution of Engineers
','INDIA'),
('Institution of Valuers
','INDIA'),
('Professional Social Workers Association
','INDIA'),
('Society of Indian Law Firms
','INDIA'),
('Society of EMC Engineers','INDIA'),
('United Nurses Association','INDIA')

select * from profession
insert into Profession(Prof_Name,Prof_Country) values
('AACE International','USA'),
('Acoustical Society of America','USA'),
('Aerobics and Fitness Association of America','USA'),
('AHS International','USA'),
('AIGA','USA'),
('Air Movement and Control Association','USA'),
('Americas Health Rankings','USA'),
('American Academy of Financial Management','USA'),
('American Academy of Actuaries','USA'),
('American Academy of Environmental Engineers and Scientists','USA'),
('American Academy of Religion','USA'),
('American Alliance of Museums','USA'),
('American Anthropological Association','USA'),
('American Association for Applied Linguistics','USA'),
('American Association for Laboratory Animal Science','USA'),
('American Association for Marriage and Family Therapy','USA'),
('American Association for Public Opinion Research','USA'),
('American Association for State and Local History','USA'),
('American Association of Airport Executives','USA'),
('American Association of Cereal Chemists','USA'),
('American Association of Colleges of Pharmacy','USA'),
('American Association of Family and Consumer Sciences','USA'),
('American Association of Foreign Language Newspapers','USA'),
('American Association of Nurse Anesthetists','USA'),
('American Association of Physics Teachers','USA'),
('American Association of Political Consultants','USA'),
('American Association of Professional Landmen','USA'),
('American Association of School Administrators','USA'),
('American Association of State Climatologists','USA'),
('American Association of University Professors','USA'),
('American Association of University Women','USA'),
('American Board of Opticianry','USA'),
('American Business Womens Association','USA'),
('American College of Healthcare Executives','USA'),
('American College of Medical Informatics','USA'),
('American College of Medical Toxicology','USA'),
('American College of Nutrition','USA'),
('American College of Veterinary Surgeons','USA'),
('American Combat Association','USA'),
('American Congress of Obstetricians and Gynecologists','USA'),
('American Congress on Surveying and Mapping','USA'),
('American Council on Exercise','USA'),
('American Counseling Association','USA'),
('American Culinary Federation','USA'),
('American Economic Association','USA'),
('American Electrology Association','USA'),
('American Ethnological Society','USA'),
('American Federation of School Administrators','USA'),
('American Fern Society','USA'),
('American Folklore Society','USA'),
('American Foreign Service Association','USA'),
('American Foundry Society','USA'),
('American Gear Manufacturers Association','USA'),
('American Gem Society','USA'),
('American Guild of Organists','USA'),
('American Health Care Association','USA'),
('American Health Lawyers Association','USA'),
('American Healthcare Professionals and Friends for Medicine in Israel','USA'),
('American Historical Association','USA'),
('American Hospital Association','USA'),
('American Institute of Aeronautics and Astronautics','USA'),
('American Institute of Architects','USA'),
('American Institute of Certified Public Accountants','USA'),
('American Institute of Floral Designers','USA'),
('American Library Association','USA'),
('American Marketing Association','USA'),
('American Medical Writers Association','USA'),
('American Meteorological Society','USA'),
('American Nuclear Society','USA'),
('American Occupational Therapy Association','USA'),
('American Ornithologists Union','USA'),
('American Osteopathic Association','USA'),
('American Philosophical Association','USA'),
('American Philosophical Society','USA'),
('American Physical Education Association','USA'),
('American Physical Society','USA'),
('American Pie Council','USA'),
('American Planning Association','USA'),
('American Political Science Association','USA'),
('American Polygraph Accreditation Board','USA'),
('American Polygraph Association','USA'),
('American Public Health Association','USA'),
('American Public Works Association','USA'),
('American Roentgen Ray Society','USA'),
('American School Health Association','USA'),
('American Screenwriters Association','USA'),
('American Society for Clinical Laboratory Science','USA'),
('American Society for Pharmacy Law','USA'),
('American Society for Public Administration','USA'),
('American Society of Agronomy','USA'),
('American Society of Appraisers','USA'),
('American Society of Clinical Hypnosis','USA'),
('American Society of Health Informatics Managers','USA'),
('American Society of Hispanic Economists','USA'),
('American Society of Landscape Architects','USA'),
('American Society of Mammalogists','USA'),
('American Society of Parasitologists','USA'),
('American Society of Pension Professionals & Actuaries','USA'),
('American Society of Plant Biologists','USA'),
('American Society of Plumbing Engineers','USA'),
('American Society of Theatre Consultants','USA'),
('American Sociological Association','USA'),
('American Sportscasters Association','USA'),
('American Statistical Association','USA'),
('American String Teachers Association','USA'),
('American Theatre Critics Association','USA'),
('American Translators Association','USA'),
('American Veterinary Medical Association','USA'),
('American Water Resources Association','USA'),
('American Water Works Association','USA'),
('Antenna Measurement Techniques Association','USA'),
('APICS','USA'),
('ASC Technology Committee','USA'),
('Asian/Pacific American Librarians Association','USA'),
('Association for Asian Studies','USA'),
('Association for Computing Machinery','USA'),
('Association for Information Science and Technology','USA'),
('Association for Library and Information Science Education','USA'),
('Association for Slavic, East European, and Eurasian Studies','USA'),
('Association for the Study of American Indian Literatures','USA'),
('Association of American Cemetery Superintendents','USA'),
('Association of American Editorial Cartoonists','USA'),
('Association of American Geographers','USA'),
('Association of Ancient Historians','USA'),
('Association of Caribbean University, Research and Institutional Libraries','USA'),
('Association of Certified Fraud Examiners','USA'),
('Association of Certified Fraud Specialists','USA'),
('Association of Directory Publishers','USA'),
('Association of Environmental and Resource Economists','USA'),
('Association of Home Appliance Manufacturers','USA'),
('Association of Performing Arts Presenters','USA'),
('Association of Professional Design Firms','USA'),
('Association of Theatrical Press Agents & Managers','USA'),
('Association of Veterinary Anaesthetists','USA'),
('American Society for Training & Development','USA'),
('Austin Area Translators and Interpreters Association','USA'),
('Authors Guild','USA'),
('Black Data Processing Associates','USA'),
('Boston Society of Architects','USA'),
('Botanical Society of America','USA'),
('American Association of Bovine Practitioners','USA'),
('Building Security Council','USA'),
('Business History Conference','USA'),
('California Association of Marriage and Family Therapists','USA'),
('California Broadcasters Association','USA'),
('Carpenters Company of the City and County of Philadelphia','USA'),
('Case Management Society of America','USA'),
('Casting Society of America','USA'),
('Casualty Actuarial Society','USA'),
('Center for Intercultural Dialogue','USA'),
('Central Eurasian Studies Society','USA'),
('Certified Health Informatics Systems Professional','USA'),
('Certified Master Inspector','USA'),
('Chartered Institute of Professional Financial Managers','USA'),
('Christian Association for Psychological Studies','USA'),
('City and Regional Magazine Association','USA'),
('College of Healthcare Information Management Executives','USA'),
('College of the State Bar of Texas','USA'),
('College Sports Information Directors of America','USA'),
('Common Computing Security Standards Forum','USA'),
('Conference of Consulting Actuaries','USA'),
('The Conference on Faith and History','USA'),
('Council of American Survey Research Organizations','USA'),
('Council of School Supervisors & Administrators','USA'),
('Council of Science Editors','USA'),
('Czechoslovak Society of Arts and Sciences','USA'),
('East Texas Historical Association','USA'),
('Ecological Society of America','USA'),
('Economic History Association','USA'),
('Entomological Society of America','USA'),
('Evangelical Philosophical Society','USA'),
('Financial Planning Association','USA'),
('Florida Public Relations Association','USA'),
('Genetics Society of America','USA'),
('Geological Society of America','USA'),
('Georgia Political Science Association','USA'),
('Gerontological Society of America','USA'),
('Group for the Advancement of Psychiatry','USA'),
('Healthcare Businesswomens Association','USA'),
('Helmsley Building','USA'),
('The Hillside Group','USA'),
('Historians of American Communism','USA'),
('History of Education Society','USA'),
('Human Factors and Ergonomics Society','USA'),
('Human Resources Management Association of Chicago','USA'),
('International Association of Black Actuaries','USA'),
('IEEE Standards Association','USA'),
('Illinois Section American Water Works Association','USA'),
('Institute for Supply Management','USA'),
('Institute of Management Consultants USA','USA'),
('Inter-University Seminar on Armed Forces and Society','USA'),
('International Communication Association','USA'),
('International Executive Resources Group','USA'),
('International Microwave Power Institute','USA'),
('International Polygraph Accreditation Board','USA'),
('International Society for Performance Improvement','USA'),
('Interstate Insurance Product Regulation Commission','USA'),
('Judson Welliver Society','USA'),
('Knowledge Management Professional Society','USA'),
('Labor and Employment Relations Association','USA')


insert into Profession (Prof_Name,Prof_Country) values
('British Psychological Society','UK'),
('British Standards Institution','UK'),
('Chartered Association of Building Engineers','UK'),
('Chartered Attitude and Behaviour','UK'),
('Chartered Institute for Securities and Investment','UK'),
('Chartered Institute of Arbitrators','UK'),
('Chartered Institute of Architectural Technologists','UK'),
('Chartered Institute of Bankers','UK'),
('Chartered Institute of Bankers in Scotland','UK'),
('Chartered Institute of Building','UK'),
('Chartered Institute of Ecology and Environmental Management','UK'),
('Chartered Institute of Environmental Health','UK'),
('Chartered Institute of Housing','UK'),
('Chartered Institute of Internal Auditors','UK'),
('Chartered Institute of Journalists','UK'),
('Chartered Institute of Legal Executives (CILEX), formerly the Institute of Legal Executives','UK'),
('Chartered Institute of Library and Information Professionals','UK'),
('Chartered Institute of Linguists','UK'),
('Chartered Institute of Logistics and Transport (CILT), formerly the Chartered Institute of Transport','UK'),
('Chartered Institute of Loss Adjusters','UK'),
('Chartered Institute of Management Accountants','UK'),
('Chartered Institute of Marketing','UK'),
('Chartered Institute of Patent Attorneys','UK'),
('Chartered Institute of Payroll Professionals','UK'),
('Chartered Institute of Personnel and Development','UK'),
('Chartered Institute of Public Finance and Accountancy','UK'),
('Chartered Institute of Public Relations','UK'),
('Chartered Institute of Purchasing & Supply','UK'),
('Chartered Institute of Taxation','UK'),
('Chartered Institution of Building Services Engineers','UK'),
('Chartered Institution of Civil Engineering Surveyors','UK'),
('Chartered Institution of Water and Environmental Management','UK'),
('Chartered Institution of Wastes Management','UK'),
('Chartered Insurance Institute','UK'),
('Chartered Management Institute','UK'),
('Chartered Quality Institute','UK'),
('Chartered Society of Designers','UK'),
('Chartered Society of Physiotherapy','UK'),
('City & Guilds of London Institute','UK'),
('College of Occupational Therapists','UK'),
('College of Optometrists','UK'),
('College of Paramedics','UK'),
('College of Teachers','UK'),
('Energy Institute','UK'),
('Engineering Council UK','UK'),
('Faculty of Actuaries','UK'),
('Faculty of Advocates','UK'),
('Geological Society of London','UK'),
('Institute of Actuaries','UK'),
('Institute of Administrative Management','UK'),
('Institute of Biomedical Science','UK'),
('Institute of Chartered Accountants in England & Walesv','UK'),
('Institute of Chartered Accountants in Ireland','UK'),
('Institute of Chartered Accountants of Scotland','UK'),
('Institute of Chartered Foresters','UK'),
('Institute of Chartered Secretaries and Administrators','UK'),
('Institute of Corporate Responsibility and Sustainability','UK'),
('Institute of Directors','UK'),
('Institute of Environmental Management and Assessment','UK'),
('Institute of Marine Engineering, Science and Technology','UK'),
('Institute of Materials, Minerals and Mining','UK'),
('Institute of Mathematics and its Applications','UK'),
('Institute of Physics','UK'),
('Institution of Chemical Engineers','UK'),
('Institution of Civil Engineers','UK'),
('Institution of Engineering and Technolog','UK'),
('Institution of Electrical Engineers','UK'),
('Institution of Incorporated Engineers','UK'),
('Institution of Engineering Designers','UK'),
('Institution of Environmental Sciences','UK'),
('Institute of Explosive Engineers','UK'),
('Institution of Gas Engineers and Managers ','UK'),
('Institution of Hospitality','UK'),
('Institution of Fire Engineers','UK'),
('Institution of Mechanical Engineers','UK'),
('Institution of Occupational Safety and Health','UK'),
('Institution of Royal Engineers','UK'),
('Institution of Structural Engineers','UK'),
('Landscape Institute','UK'),
('Law Society','UK'),
('Linnean Society of London','UK'),
('Royal Academy of Engineering','UK'),
('Royal Aeronautical Society','UK'),
('Royal Agricultural Society of England','UK'),
('Royal Anthropological Institute','UK'),
('Royal Asiatic Society','UK'),
('Royal Astronomical Society','UK'),
('Royal British Society of Sculptors','UK'),
('Royal College of Anaesthetists','UK'),
('Royal College of General Practitioners','UK'),
('Royal College of Nursing','UK'),
('Royal College of Organists','UK'),
('Royal College of Physicians and Surgeons of Glasgow','UK'),
('Royal College of Physicians of Edinburgh','UK'),
('Royal College of Physicians of London','UK'),
('Royal College of Psychiatrists','UK'),
('Royal College of Radiologists','UK'),
('Royal College of Surgeons of Edinburgh','UK'),
('Royal College of Veterinary Surgeons','UK'),
('Royal Economic Society','UK'),
('Royal Geographical Society','UK'),
('Royal Incorporation of Architects in Scotland','UK'),
('Royal Institute of British Architects','UK'),
('Royal Institute of Navigation','UK'),
('Royal Institution of Chartered Surveyors','UK'),
('Royal Institution of Naval Architects','UK'),
('Royal Meteorological Society','UK'),
('Royal Pharmaceutical Society','UK'),
('Royal Photographic Society','UK'),
('Royal Society for Asian Affairs','UK'),
('Royal Society for Public Health','UK'),
('Royal Society of Arts','UK'),
('Royal Society of Chemistry','UK'),
('Royal Society of Edinburgh','UK'),
('Royal Society of Medicine','UK'),
('Royal Society of Ulster Architects','UK'),
('Royal Statistical Society','UK'),
('Royal Town Planning Institute','UK'),
('Society for Radiological Protection','UK'),
('Society for the Environment','UK'),
('Society of Biology','UK')
('Society of Dyers and Colourists','UK'),
('Association of Accounting Technicians','UK'),
('Archives and Records Association','UK'),
('Arts Marketing Association','UK'),
('Association of British Travel Agents','UK'),
('Association for Information and Image Management','UK'),
('Association of MBAs','UK'),
('Association for Management Education and Development','UK'),
('Association of Professional Declutterers and Organisers','UK'),
('Association for Project Management','UK'),
('Association of Proposal Management Professionals','UK'),
('Association for the Scientific Study of Anomalous Phenomena','UK'),
('Association of Business Executives','UK'),
('Association of Chief Executives of Voluntary Organisations','UK'),
('Association of Cost Engineers','UK'),
('Association of International Accountants','UK'),
('Association of Taxation Technicians','UK'),
('Association of Translation Companies','UK'),
('Association of Personal Assistants','UK'),
('Association of University Administrators','UK'),
('British Association for Counselling & Psychotherapy','UK'),
('British Association of Social Workers','UK'),
('British Council for Offices','UK'),
('British Guild of Travel Writers','UK'),
('British Horse Society','UK'),
('British Institute of Facilities Management','UK'),
('British Institute for Learning and Development','UK'),
('British and International Golf Greenkeepers Association','UK'),
('British Osteopathic Association','UK'),
('Cambridge Academy of Management','UK'),
('Cambridge Association of Entrepreneurs','UK'),
('Corporation of Executives and Administrators','UK'),
('Corporate Responsibility Group','UK'),
('Direct Marketing Association','UK'),
('Driving Instructors Association','UK'),
('Fine Art Trade Guild','UK'),
('Freshwater Biological Association','UK'),
('General Teaching Council for England','UK'),
('Incorporated Society of Musicians','UK'),
('Insolvency Practitioners Association','UK'),
('Institute for Learning','UK'),
('Institute for the Management of Information Systems','UK'),
('Institute of Administrative Management','UK'),
('Institute of Asphalt Technology','UK'),
('Institute of Business Administration','UK'),
('Institute of Certified Bookkeepers','UK'),
('Institute of Chartered IT Professionals','UK'),
('Institute of Civil Protection and Emergency Management','UK'),
('Institute of Commercial Management','UK'),
('Institute of Construction Management','UK'),
('Institute of Corrosion','UK'),
('Institute of Counter Fraud Specialists','UK'),
('Institute of Economic Development','UK'),
('Institute of Enterprise and Entrepreneurs','UK'),
('Institute of Field Archaeologists','UK'),
('Institute of Fundraising','UK'),
('Institute of Groundsmanship','UK'),
('Institute of Information Security Professionals','UK'),
('Institute of Interim Management','UK'),
('Institute of Leadership & Management','UK'),
('Institute of Operations Management','UK'),
('Institute of Practitioners in Advertising','UK'),
('Institute of Professional Administrators','UK'),
('Institute of Professional Financial Managers','UK'),
('Institute of Professional Sound','UK'),
('Institute of Recruiters','UK'),
('Institute of Sales and Marketing Management','UK'),
('Institute of Scientific and Technical Communicators','UK'),
('Institute of Sound and Communications Engineers','UK'),
('Institute of Tourist Guiding','UK'),
('Institute of Trade Mark Attorneys','UK'),
('Institute of Transport Administration','UK'),
('Institution of Agricultural Engineers','UK'),
('Institution of Analysts and Programmers','UK'),
('Institution of Railway Signal Engineers','UK'),
('Institution of Sustainability Professionals','UK'),
('International Association of Hydrogeologists','UK'),
('International Compliance Association','UK'),
('International Entrepreneurs Association','UK'),
('International Glassfibre Reinforced Concrete Association ','UK'),
('International Society of Typographic Designers','UK'),
('British Typographers Guild','UK'),
('Society of Typographic Designers','UK'),
('Law Society of Scotland','UK'),
('Minor Metals Trade Association','UK'),
('Museums Association','UK'),
('Orthodontic Technicians Association','UK'),
('Palaeontological Association','UK'),
('Records Management Society','UK'),
('Research Quality Association','UK'),
('The National Photographic Society','UK'),
('Security Institute','UK'),
('Society of Business Practitioners','UK'),
('Society of Indexers','UK'),
('Society of Trust and Estate Practitioners','UK'),
('UK Council for Psychotherapy','UK'),
('UK IT Association','UK'),
('United Kingdom Cast Stone Association','UK'),
('Association of Chartered Certified Accountants','UK'),
('Association of Corporate Treasurers','UK'),
('British Computer Society','UK'),
('British Institute of Facilities Management','UK'),
('British Psychological Society','UK'),
('British Standards Institution','UK'),
('Chartered Association of Building Engineers','UK'),
('Chartered Attitude and Behaviour','UK'),
('Chartered Institute for Securities and Investment','UK'),
('Chartered Institute of Arbitrators','UK'),
('Chartered Institute of Architectural Technologists','UK'),
('Chartered Institute of Bankers','UK'),
('Chartered Institute of Bankers in Scotland','UK'),
('Chartered Institute of Building','UK'),
('Chartered Institute of Ecology and Environmental Management','UK'),
('Chartered Institute of Environmental Health','UK'),
('Chartered Institute of Housing','UK'),
('Chartered Institute of Internal Auditors','UK'),
('Chartered Institute of Journalists','UK'),
('Chartered Institute of Legal Executives','UK'),
('Chartered Institute of Library and Information Professionals','UK'),
('Chartered Institute of Linguists','UK'),
('Chartered Institute of Logistics and Transport','UK'),
('Chartered Institute of Loss Adjusters','UK'),
('Chartered Institute of Management Accountants','UK'),
('Chartered Institute of Marketing','UK'),
('Chartered Institute of Patent Attorneys','UK'),
('Chartered Institute of Payroll Professionals','UK'),
('Chartered Institute of Personnel and Development','UK'),
('Chartered Institute of Public Finance and Accountancy','UK'),
('Chartered Institute of Public Relations','UK'),
('Chartered Institute of Purchasing & Supply','UK'),
('Chartered Institute of Taxation','UK'),
('Chartered Institution of Building Services Engineers','UK'),
('Chartered Institution of Civil Engineering Surveyors','UK'),
('Chartered Institution of Water and Environmental Management','UK'),
('Chartered Institution of Wastes Management','UK'),
('Chartered Insurance Institute','UK'),
('Chartered Management Institute','UK'),
('Chartered Quality Institute','UK'),
('Chartered Society of Designers','UK'),
('Chartered Society of Physiotherapy','UK'),
('City & Guilds of London Institute','UK'),
('College of Occupational Therapists','UK'),
('College of Optometrists','UK'),
('College of Paramedics','UK'),
('College of Teachers','UK'),
('Energy Institute','UK'),
('Engineering Council UK','UK'),
('Faculty of Actuaries','UK'),
('Faculty of Advocates','UK'),
('Geological Society of London','UK'),
('Institute of Actuaries','UK'),
('Institute of Administrative Management','UK'),
('Institute of Biomedical Science','UK'),
('Institute of Chartered Accountants','UK'),
('Institute of Chartered Accountants in Ireland','UK'),
('Institute of Chartered Accountants of Scotland','UK'),
('Institute of Chartered Foresters','UK'),
('Institute of Chartered Secretaries and Administrators','UK'),
('Institute of Corporate Responsibility and Sustainability','UK'),
('Institute of Directors','UK'),
('Institute of Environmental Management and Assessment','UK'),
('Institute of Marine Engineering, Science and Technology','UK'),
('Institute of Materials, Minerals and Mining','UK'),
('Institute of Mathematics and its Applications','UK'),
('Institute of Physics','UK'),
('Institution of Chemical Engineers','UK'),
('Institution of Civil Engineers','UK'),
('Institution of Engineering and Technology','UK'),
('Institution of Electrical Engineers','UK'),
('Institution of Incorporated Engineers','UK'),
('Institution of Engineering Designers','UK'),
('Institution of Environmental Sciences','UK'),
('Institute of Explosive Engineers','UK'),
('Institution of Gas Engineers and Managers','UK'),
('Institution of Hospitality','UK'),
('Institution of Fire Engineers','UK'),
('Institution of Mechanical Engineers','UK'),
('Institution of Occupational Safety and Health','UK'),
('Institution of Royal Engineers','UK'),
('Institution of Structural Engineers','UK'),
('Landscape Institute','UK'),
('Law Society, The','UK'),
('Linnean Society of London ','UK'),
('Royal Academy of Engineering','UK'),
('Royal Aeronautical Society','UK'),
('Royal Agricultural Society of England','UK'),
('Royal Anthropological Institute','UK'),
('Royal Asiatic Society','UK'),
('Royal Astronomical Society ','UK'),
('Royal British Society of Sculptors','UK'),
('Royal College of Anaesthetists','UK'),
('Royal College of General Practitioners','UK'),
('Royal College of Nursing','UK'),
('Royal College of Organists','UK'),
('Royal College of Physicians and Surgeons of Glasgow','UK'),
('Royal College of Physicians of Edinburgh','UK'),
('Royal College of Physicians of London','UK'),
('Royal College of Psychiatrists','UK'),
('Royal College of Radiologists','UK'),
('Royal College of Surgeons of Edinburgh','UK'),
('Royal College of Veterinary Surgeons','UK'),
('Royal Economic Society','UK'),
('Royal Geographical Society','UK'),
('Royal Incorporation of Architects','UK'),
('Royal Institute of British Architects','UK'),
('Royal Institute of Navigation','UK'),
('Royal Institution of Chartered Surveyors','UK'),
('Royal Institution of Naval Architects','UK'),
('Royal Meteorological Society','UK'),
('Royal Pharmaceutical Society','UK'),
('Royal Photographic Society','UK'),
('Royal Society for Asian Affairs','UK'),
('Royal Society for Public Health','UK'),
('Royal Society of Arts','UK'),
('Royal Society of Chemistry','UK'),
('Royal Society of Edinburgh','UK'),
('Royal Society of Medicine','UK'),
('Royal Society of Ulster Architects','UK'),
('Royal Statistical Society','UK'),
('Royal Town Planning Institute','UK'),
('Society for Radiological Protection','UK'),
('Society for the Environment','UK'),
('Society of Biology','UK'),
('Society of Dyers and Colourists','UK')



/*Create table of Industry*/
create table Industry
(
Industry_ID int identity(1,1) primary key,
Industry_Name nvarchar(max) not null
)

/* create table for Syllabus*/
create table Syllabus
(
Syllabus_ID int identity(1,1) primary key,
Syllabus_Name nvarchar(max) not null,
Syllabus_Detail nvarchar(max) not null
)

select * from Syllabus


/*Create table of Admin*/
create table AdminMaster
(
Name nvarchar(max) not null,
Username nvarchar(50) primary key,
Password nvarchar(max) not null,
Gender nvarchar(max) not null,
Email nvarchar(50),
Contact nvarchar(max) not null,
Address nvarchar(max) not null,
Pincode int,
UNIQUE(Email)
)

/*Create table of user */
create table UserMaster
(
UID int identity(1,1) primary key,
Username nvarchar(max) not null,
Email nvarchar(50) ,
Password nvarchar(max) not null,
Unique(Email)
)

/*create table of questions*/
create table Questions
(
Ques_ID int identity(1,1) primary key,
Question nvarchar(max) not null,
PicPath nvarchar(max) not null,
PostedBy nvarchar(max) not null,
Ques_Date datetime default getdate()
)

mytab
/*Create table of Answers*/
create table Answers
(
Ans_ID int identity (1,1) primary key,
Answer nvarchar(max) not null,
Answer_Detail nvarchar(max) not null,
Mp3_Name nvarchar(max) not null,
Status char(1) not null,
Ques_ID int references Questions(Ques_ID),
PostedBy nvarchar(max) not null,
Ans_Date datetime default getdate()
)


select * from questions
select * from Answers

SELECT * FROM answers ORDER BY RAND()
SELECT TOP 4 Answer,Answer_Detail,Mp3_Name,Status FROM Answers where ques_id=1 order BY NEWID()


Select Status from answers where answer='dog'

Select Status,Answer_Detail,answer from answers where Ques_ID=1 and Answer='lion'


update  answers set Status='R' where Ans_ID=1
select * from Questions
select * from Answers

select  * from userMaster


select * from AdminMaster
truncate table usermaster
